# `torch.tensor` operations

In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[2.4059e-05, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.9946e-05, 0.0000e+00, 2.2421e-44, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 0.0000e+00, 3.1109e-43]])


In [3]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [4]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [5]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[ 3.9698e-05,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -0.0000e+00,  1.5912e+00]],

        [[ 3.6893e+19,  1.8732e+00, -2.0000e+00],
         [ 1.7064e+00,  1.0842e-19,  1.7735e+00]]])
torch.Size([2, 2, 3])
tensor([[[1.7377e-09, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.8566e-09, 0.0000e+00]],

        [[0.0000e+00, 9.5507e-38, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 3.1109e-43]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [6]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [7]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [9]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [10]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [11]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [12]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6]])
# Concatenate along the 0th dimension
result = torch.cat((x, y), dim=0)
print(result)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [14]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6]])
# Stack along a new dimension (dimension 0)
result = torch.stack((x, y), dim=0)
print(result)

RuntimeError: stack expects each tensor to be equal size, but got [2, 2] at entry 0 and [1, 2] at entry 1

In [15]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.7220, 0.8217, 0.2612, 0.7375],
        [0.8328, 0.8444, 0.2941, 0.3788]])
tensor([[1.4439, 1.6434, 0.5224, 1.4750],
        [1.6657, 1.6888, 0.5882, 0.7576]])


In [16]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]]])
tensor([[[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]]])
tensor([[[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]]])


In [17]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(4, 3)    # dimensions must match last-to-first

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [ ]:
c = a * torch.rand(2, 3) # both 3rd & 2nd dims different

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [ ]:
d = a * torch.rand((0, ))   # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (0) at non-singleton dimension 2

In [19]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [21]:
type(agg)

torch.Tensor

In [22]:
type(agg.item())

float

In [27]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [28]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [29]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [30]:
n = np.ones(5)
t = torch.from_numpy(n)

In [31]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [32]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [34]:
a = torch.rand(3, 224, 224)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 224, 224])
torch.Size([1, 3, 224, 224])


In [35]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.5837, 0.9664, 0.4801, 0.8534, 0.5625, 0.6495, 0.5646, 0.5609, 0.6534,
         0.1190, 0.6315, 0.4689, 0.0258, 0.6892, 0.1718, 0.9357, 0.6808, 0.9962,
         0.2143, 0.7576]])
torch.Size([20])
tensor([0.5837, 0.9664, 0.4801, 0.8534, 0.5625, 0.6495, 0.5646, 0.5609, 0.6534,
        0.1190, 0.6315, 0.4689, 0.0258, 0.6892, 0.1718, 0.9357, 0.6808, 0.9962,
        0.2143, 0.7576])
torch.Size([2, 2])
torch.Size([2, 2])


In [36]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[0.3967, 0.3967],
         [0.7630, 0.7630],
         [0.4042, 0.4042]],

        [[0.3967, 0.3967],
         [0.7630, 0.7630],
         [0.4042, 0.4042]],

        [[0.3967, 0.3967],
         [0.7630, 0.7630],
         [0.4042, 0.4042]],

        [[0.3967, 0.3967],
         [0.7630, 0.7630],
         [0.4042, 0.4042]]])


In [38]:
a = torch.ones(4, 3, 2)
b = torch.rand(3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

torch.Size([3, 1])
tensor([[[0.8632, 0.8632],
         [0.3693, 0.3693],
         [0.4282, 0.4282]],

        [[0.8632, 0.8632],
         [0.3693, 0.3693],
         [0.4282, 0.4282]],

        [[0.8632, 0.8632],
         [0.3693, 0.3693],
         [0.4282, 0.4282]],

        [[0.8632, 0.8632],
         [0.3693, 0.3693],
         [0.4282, 0.4282]]])


In [39]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


In [44]:
a = torch.rand(2, 1, 2, 3)
print("a values: \n", a)

a values: 
 tensor([[[[0.8342, 0.6184, 0.3863],
          [0.9346, 0.3704, 0.6752]]],


        [[[0.9559, 0.7080, 0.3372],
          [0.8969, 0.3694, 0.4259]]]])


In [45]:
a.flatten()

tensor([0.8342, 0.6184, 0.3863, 0.9346, 0.3704, 0.6752, 0.9559, 0.7080, 0.3372,
        0.8969, 0.3694, 0.4259])

# Logistic regression with PyTorch

In [48]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import torch
import torch.nn as nn
import torch.optim as optim

import warnings
# filter warnings
warnings.filterwarnings('ignore')

## Data Procesing

In [49]:
# Reading data

df = pd.read_csv('../data/Module_1_Lecture_2_Class_Spaceship_Titanic.csv')
df = df.set_index('PassengerId')

TARGET = 'Transported'
FEATURES = [col for col in df.columns if col != TARGET]

In [50]:
imputer_cols = ["Age", "FoodCourt", "ShoppingMall", "Spa", "VRDeck", "RoomService"]
imputer = SimpleImputer(strategy='median')
imputer.fit(df[imputer_cols])

imputed = pd.DataFrame(
    imputer.transform(df[imputer_cols]),
    columns=imputer_cols,
    index=df.index,
)

df = (
    df
    .assign(
        **{col: imputed[col] for col in imputer_cols},
        HomePlanet=lambda d: d["HomePlanet"].fillna('Gallifrey'),
        Destination=lambda d: d["Destination"].fillna('Skaro'),
        CryoSleep_is_missing=lambda d: d["CryoSleep"].isna().astype(int),
        VIP_is_missing=lambda d: d["VIP"].isna().astype(int),
        CryoSleep=lambda d: d["CryoSleep"].fillna(False).astype(int),
        VIP=lambda d: d["VIP"].fillna(False).astype(int),
        **{TARGET: lambda d: d[TARGET].astype(int)},
    )
)

dummies = pd.get_dummies(df.loc[:, ['HomePlanet', 'Destination']], dtype=int)

df = (
    pd.concat([df, dummies], axis=1)
    .drop(columns=['HomePlanet', 'Destination', 'Name', 'Cabin'])
)

In [51]:
# Train/test split

X = df.drop(TARGET , axis =1 ).values
y = df[TARGET].values

X_train , X_test , y_train , y_test = train_test_split(X, y, random_state = 42, test_size =0.33, stratify=y)

In [52]:
# Convert numpy arrays to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)

X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

## Layers use-cases

In [53]:
m = nn.Linear(5, 3)
input = torch.randn(4, 5)
output = m(input)

print('Input:', input, f'shape {input.shape}', sep='\n')
print('\nOutput:', output, f'shape {output.shape}', sep='\n')

Input:
tensor([[ 0.1611,  0.7373, -1.8162, -2.1066, -0.3453],
        [ 1.0158, -0.2085, -1.0191, -1.3549, -1.6714],
        [ 1.1871, -0.5334, -1.8501, -0.4716,  1.2966],
        [-0.0437, -0.8592, -0.6624,  1.7353,  0.4676]])
shape torch.Size([4, 5])

Output:
tensor([[ 0.1132,  0.9748,  0.8660],
        [-0.2542,  0.3422, -0.5651],
        [-0.5270,  0.1863,  0.5592],
        [-0.8116, -0.8297,  0.1598]], grad_fn=<AddmmBackward0>)
shape torch.Size([4, 3])


In [54]:
t = torch.randn(4)
print('Input: ', t)
print('Applying sigmoid: ', torch.sigmoid(t))

Input:  tensor([-0.9388,  0.5605,  0.0513,  0.6223])
Applying sigmoid:  tensor([0.2811, 0.6366, 0.5128, 0.6507])


## Model

In [ ]:
# Define the logistic regression model

class LogisticRegression(nn.Module):
    def __init__(self, input_dim):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_dim, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear(x)
        out = self.sigmoid(out)
        return out

In [90]:
# Instantiate the model
input_dim = X_train.shape[1]
model = LogisticRegression(input_dim)

# Define loss function and optimizer
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [81]:
# Train the model
num_epochs = 100
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_train)
    loss = criterion(outputs.squeeze(), y_train)
    
    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch+1) % 5 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [5/100], Loss: 8.7764
Epoch [10/100], Loss: 7.4931
Epoch [15/100], Loss: 10.9911
Epoch [20/100], Loss: 14.1090
Epoch [25/100], Loss: 14.0819
Epoch [30/100], Loss: 12.1993
Epoch [35/100], Loss: 10.1056
Epoch [40/100], Loss: 9.8398
Epoch [45/100], Loss: 9.4243
Epoch [50/100], Loss: 7.9921
Epoch [55/100], Loss: 7.7009
Epoch [60/100], Loss: 9.7184
Epoch [65/100], Loss: 9.0388
Epoch [70/100], Loss: 14.8085
Epoch [75/100], Loss: 13.5900
Epoch [80/100], Loss: 13.3353
Epoch [85/100], Loss: 12.2513
Epoch [90/100], Loss: 10.8752
Epoch [95/100], Loss: 9.6742
Epoch [100/100], Loss: 9.3091


In [83]:
# Test the model
with torch.no_grad():
    y_pred = model(X_test).squeeze().numpy().round()

accuracy_score(y_test, y_pred)

0.7835482746601603